# Get current user
GET 'http://localhost:8080/auth/me

#POST /auth/register creates a new user
POST 'http://localhost:8080/auth/register
Content-Type: application/json
{
  "email": "email",
  "password": "password",
  "role": "role",
  "section": "section"
}

# POST /auth/register creates a new user
POST 'http://localhost:8080/auth/login
Content-Type: application/json
{
  "email": "email",
  "password": "password",
}

# Logout and removes cookie
POST 'http://localhost:8080/auth/logout
