### Ingest components from CSV file
POST http://localhost:8080/ingest/components
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="components.csv"
Content-Type: text/csv

< ./components.csv
--boundary--

### Ingest end items from CSV file
POST http://localhost:8080/ingest/end-items
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="end-items.csv"
Content-Type: text/csv

< ./end-items.csv
--boundary--
